Repository openshift-knative/kn-plugin-func, pull requests merged in 2022-11, with the labels that each got.

#379 fix: Quarkus patch
  openshift/patches/0003-quarkus-productized.patch
Labels: approved, lgtm

#390 chore: update quarkus patch
  openshift/patches/0003-quarkus-productized.patch
Labels: approved, lgtm

#395 Cherrypick buildpack fixes from upstream
  buildpacks/builder.go
  buildpacks/builder_test.go
  go.mod
Labels: approved

#400 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#401 fix: SocatImage var name
  cmd/root.go
  cmd/root_test.go
  k8s/dialer.go
Labels: approved, lgtm

#405 fix: Quarkus patch
  openshift/patches/0003-quarkus-productized.patch
Labels: approved, lgtm
