Repository openshift-knative/kn-plugin-func, pull requests merged in 2022-10, with the labels that each got.

#332 fix: make socatImage linker setable
  k8s/dialer.go
Labels: approved, lgtm

#335 chore: update quarkus patch
  openshift/patches/0003-quarkus-productized.patch
Labels: approved, lgtm

#334 [serveless-1.25] changed func-deploy task to use kn from serverless operator
  pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
Labels: approved, lgtm

#339 chore: update e2e runtime test patch
  openshift/patches/0004-ci-e2e-runtime.patch
Labels: approved, lgtm

#341 chore: change package name in tekton patch
  openshift/patches/0001-tekton-tasks.patch
Labels: approved, lgtm

#342 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#343 fix: remove socat image patch
  openshift/patches/0006-patch-images.patch
Labels: approved, lgtm

#345 fix: seccomp patch
  openshift/patches/0005-seccomp-osh.patch
Labels: approved, lgtm

#346 chore: update quarkus patch
  openshift/patches/0003-quarkus-productized.patch
Labels: approved, lgtm

#348 fix: seccomp patch
  openshift/patches/0005-seccomp-osh.patch
Labels: approved, lgtm

#350 chore: add openshift pipelines hack script override
  openshift/overrides/hack/openshift-pipelines.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#351 chore: update Quarkus patch
  openshift/patches/0003-quarkus-productized.patch
Labels: lgtm

#355 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#356 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#364 chore: add func-deploy task patch
  openshift/patches/00006-func-deploy.patch
Labels: approved, lgtm
