Repository openshift-knative/kn-plugin-func, pull requests merged in 2023-08, with the labels that each got.

#626 Update Quarkus Patch to 3.2.3.Final
  openshift/patches/0002-quarkus-productized.patch
Labels: approved, lgtm

#635 Update 0002-quarkus-productized.patch
  openshift/patches/0002-quarkus-productized.patch
Labels: approved, lgtm

#643 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#646 Fix refs
  .github/workflows/test-e2e-oncluster-runtime.yaml
  .github/workflows/test-e2e-oncluster.yaml
  .github/workflows/test-e2e-runtime.yaml
  .github/workflows/test-e2e.yaml
  pkg/pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks-pac.yaml
  pkg/pipelines/resources/tekton/task/func-deploy/0.1/func-deploy-pac.yaml
  pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i-pac.yaml
  pkg/pipelines/tekton/templates.go
Labels: approved

#649 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream

#651 [serverless-1.30] Fix tekton task reference url
  pkg/pipelines/tekton/templates.go
Labels: approved, lgtm

#656 fix: RH pull secrets for KinD
  openshift/patches/0007-rh-reg-pull-secrets
Labels: approved, lgtm

#662 chore: include ca certs in release process
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#668 chore: release-next-ci is auto-approved
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#671 Update 0002-quarkus-productized.patch
  openshift/patches/0002-quarkus-productized.patch
Labels: approved, lgtm
