Repository openshift-knative/kn-plugin-func, pull requests merged in 2024-10, with the labels that each got.

#917 [serverless-1.34] Remove unnecessary annotations from Pipeline-as-Code template [SRVOCF-626]
  pkg/pipelines/tekton/templates_s2i.go
Labels: approved, lgtm

#921 [release-v1.15] Rerun Dockerfile generator
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/func-util/Dockerfile
  openshift/scripts/generate-dockerfiles.sh
  rpms.lock.yaml
Labels: approved, lgtm

#922 [serverless-1.34] Set default value for REGISTRY param on func-s2i task [SRVOCF-628]
  pkg/pipelines/tekton/tasks.go
Labels: approved, lgtm

#919 [release-v1.15] Add Konflux configurations
  .konflux/applications/serverless-operator-135/components/imagerepositories/kn-plugin-func-func-util-115.yaml
  .konflux/applications/serverless-operator-135/components/kn-plugin-func-func-util-115.yaml
  .konflux/applications/serverless-operator-135/serverless-operator-135.yaml
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .tekton/docker-build.yaml
  .tekton/kn-plugin-func-func-util-115-pull-request.yaml
  .tekton/kn-plugin-func-func-util-115-push.yaml
Labels: approved, lgtm, do-not-merge/hold

#926 [release-v1.15] Fixes
  cmd/repository_test.go
  pkg/functions/repositories_test.go
  pkg/oci/containerize_test.go
  pkg/oci/testdata/test-links/absoluteLink
  pkg/oci/testdata/test-links/absoluteLinkWindows
  pkg/pipelines/tekton/tasks.go
  pkg/pipelines/tekton/templates_s2i.go
  pkg/testing/testing.go
  rpms.lock.yaml
Labels: approved, lgtm

#933 Patch script to include webconsole nodejs tekton pipeline to tkn-tasks
  openshift/scripts/include-devconsole-pipeline.sh
Labels: approved, lgtm

#934 [serverless-1.34] Fix symlink path separators
  pkg/builders/s2i/builder.go
  pkg/pipelines/tekton/pipelines_provider.go
Labels: approved, lgtm

#941 [release-v1.15] Add Konflux configurations
  .tekton/kn-plugin-func-func-util-115-pull-request.yaml
  .tekton/kn-plugin-func-func-util-115-push.yaml
Labels: approved, lgtm

#945 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm
