Repository openshift-knative/kn-plugin-func, pull requests merged in 2024-11, with the labels that each got.

#958 [release-1.34] Make array when filters is nil
  cmd/subscribe.go
Labels: approved, lgtm

#959 [release-1.15] Make array when filters is nil
  cmd/subscribe.go
Labels: lgtm

#967 Fix symlink path separators
  pkg/builders/s2i/builder.go
  pkg/pipelines/tekton/pipelines_provider.go
Labels: approved

#974 [release-v1.15] fix: set DOCKER_CONFIG prior to build
  generate/zz_filesystem_generated.go
  pkg/pipelines/tekton/tasks.go
Labels: approved

#975 [release-v1.15] Include license in image
  openshift/ci-operator/knative-images/func-util/Dockerfile
Labels: approved, lgtm

#944 [release-v1.15] Add Konflux configurations
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .tekton/kn-plugin-func-func-util-115-pull-request.yaml
  .tekton/kn-plugin-func-func-util-115-push.yaml
Labels: lgtm
