Repository openshift-knative/kn-plugin-func, pull requests merged in 2024-09, with the labels that each got.

#856 Update 0006-s2i-task-images.patch
  openshift/patches/0006-s2i-task-images.patch
Labels: approved, lgtm

#860 Add Dockerfile generator
  openshift/ci-operator/build-image/Dockerfile
  openshift/project.yaml
  openshift/scripts/generate-dockerfiles.sh
Labels: approved, lgtm

#862 Fix splicing for dockerfile generate
  openshift/scripts/generate-dockerfiles.sh
Labels: approved, lgtm

#868 [serverless-1.34] More granular image references
  pkg/pipelines/tekton/tasks.go
Labels: approved, lgtm

#871 Use func-util template in dockerfile generator
  openshift/scripts/generate-dockerfiles.sh
Labels: approved, lgtm

#872 Use RHEL 8 for builder base for func-util image
  openshift/scripts/generate-dockerfiles.sh
Labels: approved, lgtm

#877 Update e2e_oncluster_tests.sh
  openshift/e2e_oncluster_tests.sh
Labels: approved, lgtm

#881 Update func-util CI image
  openshift/ci-operator/knative-images/func-util/Dockerfile
Labels: approved, lgtm

#884 [serverless-1.34] Set func-utils image from FUNC_UTILS_IMG envvar
  Makefile
  openshift/e2e_oncluster_tests.sh
Labels: approved, lgtm

#887 [serverless-1.34] patch bash image
  pkg/pipelines/tekton/tasks.go
Labels: approved, lgtm

#886 [serverless-1.34] enable go s2i test
  test/oncluster/scenario_runtime_test.go
Labels: approved, lgtm

#888 [serverless-1.34] Update docker dependency
  go.mod
  go.sum
Labels: approved, lgtm

#890 Add scripts to mirror upstream branches
  openshift/release/apply-midstream-patches.sh
  openshift/release/common.sh
  openshift/release/create-release-branch.sh
  openshift/release/mirror-upstream-branches.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#895 Run mirror-branches as part of update-to-head
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#896 Force fetching upstream tags to not complain about existing tags with same name in origin
  openshift/release/mirror-upstream-branches.sh
Labels: approved, lgtm

#897 Update update-to-head.sh
  openshift/release/update-to-head.sh
Labels: approved

#898 Update update-to-head.sh
  openshift/release/update-to-head.sh
Labels: approved

#900 Exclude 1.15 from upstream branch mirroring
  openshift/release/mirror-upstream-branches.sh
Labels: approved, lgtm

#912 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm

#911 [serverless-1.34] fix: allow sub-pkgs in Go functions
  generate/zz_filesystem_generated.go
  pkg/builders/s2i/assemblers.go
  pkg/functions/runner.go
  pkg/oci/containerize_go.go
  templates/go/scaffolding/instanced-cloudevents/go.mod
  templates/go/scaffolding/instanced-cloudevents/main.go
  templates/go/scaffolding/instanced-http/go.mod
  templates/go/scaffolding/instanced-http/main.go
  templates/go/scaffolding/static-cloudevents/go.mod
  templates/go/scaffolding/static-cloudevents/main.go
  templates/go/scaffolding/static-http/go.mod
  templates/go/scaffolding/static-http/main.go
Labels: approved, lgtm
