Repository openshift-knative/kn-plugin-func, pull requests merged in 2024-12, with the labels that each got.

#989 Update owners file to reflect current state
  OWNERS
Labels: approved, lgtm

#981 [release-v1.15] Add Konflux configurations
  .konflux/applications/serverless-operator-135/components/kn-plugin-func-func-util-115.yaml
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
Labels: approved, lgtm

#990 Update CI images base
  openshift/scripts/generate-dockerfiles.sh
Labels: approved, lgtm

#999 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm

#1001 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm

#1005 [release-v1.15] Disable syft github-actions-usage-cataloger
  .syft.yaml
Labels: approved, lgtm

#1016 [release-v1.15] Update golang.org/x/crypto to 0.31.0
  go.mod
  go.sum
Labels: approved, lgtm

#1017 [release-v1.15] fix: add case for DNS resolve fail in TestDialUnreachable
  pkg/k8s/dialer_test.go
Labels: approved, lgtm

#1015 [release-v1.16] Update golang.org/x/crypto to 0.31.0
  go.mod
  go.sum
Labels: approved, lgtm

#1014 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved
