Repository openshift-knative/kn-plugin-func, pull requests merged in 2025-03, with the labels that each got.

#1160 [release-v1.17] Update Konflux configurations
  rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#1170 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm

#1159 [release-v1.16] Update Konflux configurations
  .tekton/kn-plugin-func-func-util-116-pull-request.yaml
  .tekton/kn-plugin-func-func-util-116-push.yaml
  rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#1173 [release-v1.16] Update Konflux configurations
  rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#1176 [release-v1.17] Update Konflux configurations
  rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#1175 [release-v1.15] Update Konflux configurations
  rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#1178 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved

#1187 [release-v1.15] Update Konflux configurations
  .tekton/kn-plugin-func-func-util-115-pull-request.yaml
  .tekton/kn-plugin-func-func-util-115-push.yaml
Labels: approved, lgtm, ok-to-test

#1188 [release-v1.16] Update Konflux configurations
  .tekton/kn-plugin-func-func-util-116-pull-request.yaml
  .tekton/kn-plugin-func-func-util-116-push.yaml
Labels: approved, lgtm, ok-to-test

#1193 [release-v1.15] Update Konflux configurations
  rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#1194 [release-v1.16] Update Konflux configurations
  .tekton/kn-plugin-func-func-util-116-pull-request.yaml
  .tekton/kn-plugin-func-func-util-116-push.yaml
  rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#1189 [release-v1.17] Update Konflux configurations
  .tekton/kn-plugin-func-func-util-117-pull-request.yaml
  .tekton/kn-plugin-func-func-util-117-push.yaml
  rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#1215 [release-v1.15] Bump gunicorn to 23.0.0
  generate/zz_filesystem_generated.go
  templates/python/flask/requirements.txt
  templates/python/wsgi/requirements.txt
Labels: approved

#1219 [release-v1.15] Update Konflux configurations
  .tekton/docker-build.yaml
  rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#1224 [release-v1.15] Bump paketo builders to "latest"
  pkg/builders/buildpacks/builder.go
Labels: approved, lgtm
