Repository openshift-knative/kn-plugin-func, pull requests merged in 2025-01, with the labels that each got.

#1035 Bump deps
  go.mod
  go.sum
Labels: approved, lgtm

#1044 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test

#1003 [release-v1.15] Add Konflux configurations
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .konflux/applications/serverless-operator-135/tests/override-snapshot-ec-test.yaml
  .tekton/kn-plugin-func-func-util-115-pull-request.yaml
  .tekton/kn-plugin-func-func-util-115-push.yaml
  openshift/ci-operator/build-image/Dockerfile
  rpms.lock.yaml
Labels: approved, lgtm

#1058 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test

#1060 [release-v1.15] Update Konflux configurations
  .konflux/applications/serverless-operator-135/serverless-operator-135.yaml
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .konflux/applications/serverless-operator-135/tests/override-snapshot-ec-test.yaml
Labels: needs-ok-to-test

#1067 [release-v1.15] fix release branch detection on midstream
  hack/allocate.sh
Labels: approved

#1065 [release-v1.17] Create test symlinks dynamically
  pkg/oci/containerize_test.go
  pkg/oci/testdata/test-links/absoluteLink
  pkg/oci/testdata/test-links/absoluteLinkWindows
Labels: approved, lgtm

#1064 [release-v1.16] Create test symlinks dynamically
  pkg/oci/containerize_test.go
  pkg/oci/testdata/test-links/absoluteLink
  pkg/oci/testdata/test-links/absoluteLinkWindows
Labels: approved

#1059 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test
