Repository openshift-knative/kn-plugin-func, pull requests merged in 2025-04, with the labels that each got.

#1238 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm

#1202 [release-v1.17] Update Konflux configurations
  rpms.lock.yaml
Labels: approved, lgtm

#1222 [release-v1.16] Update Konflux configurations
  .konflux/applications/serverless-operator-136/components/kn-plugin-func-func-util-116.yaml
  rpms.lock.yaml
Labels: approved, lgtm

#1248 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm

#1257 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm

#1244 [release-v1.16] Update Konflux configurations
  .tekton/docker-build.yaml
Labels: approved

#1272 [release-v1.16] bump Dockerfile.utils to go 1.23
  Dockerfile.utils
Labels: approved, lgtm

#1264 [release 1.15] bump golang.org/x/net
  go.mod
  go.sum
Labels: approved, lgtm

#1271 [release-v1.16] Update Konflux configurations
  .tekton/kn-plugin-func-func-util-116-pull-request.yaml
  .tekton/kn-plugin-func-func-util-116-push.yaml
Labels: approved, lgtm

#1247 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, ok-to-test
