Repository openshift-knative/kn-plugin-func, pull requests merged in 2025-02, with the labels that each got.

#1069 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm

#1038 [release-v1.16] Add Konflux configurations
  .konflux/applications/serverless-operator-136/components/imagerepositories/kn-plugin-func-func-util-116.yaml
  .konflux/applications/serverless-operator-136/components/kn-plugin-func-func-util-116.yaml
  .tekton/docker-build.yaml
  .tekton/kn-plugin-func-func-util-116-pull-request.yaml
  .tekton/kn-plugin-func-func-util-116-push.yaml
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/func-util/Dockerfile
  openshift/images.yaml
  rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#1061 [release-v1.17] Update Konflux configurations
  .konflux/applications/serverless-operator-137/components/imagerepositories/kn-plugin-func-func-util-117.yaml
  .konflux/applications/serverless-operator-137/components/kn-plugin-func-func-util-117.yaml
  .tekton/docker-build.yaml
  .tekton/kn-plugin-func-func-util-117-pull-request.yaml
  .tekton/kn-plugin-func-func-util-117-push.yaml
  openshift/ci-operator/knative-images/func-util/Dockerfile
  openshift/images.yaml
Labels: needs-ok-to-test

#1086 Run update-codegen.sh in auto-dep-updater
  .renovaterc
Labels: approved

#1087 broker -> Broker fix, bump versions
  hack/allocate.sh
  hack/install-binaries.sh
Labels: approved, lgtm

#1088 Update python component versions + CA certificates + ZZ file
  generate/zz_filesystem_generated.go
  templates/certs/ca-certificates.crt
  templates/python/flask/requirements.txt
  templates/python/wsgi/requirements.txt
Labels: approved, lgtm

#1070 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, ok-to-test

#1094 [release-v1.17] Update Konflux configurations
  .tekton/kn-plugin-func-func-util-117-pull-request.yaml
  .tekton/kn-plugin-func-func-util-117-push.yaml
  openshift/ci-operator/knative-images/func-util/Dockerfile
Labels: lgtm, needs-ok-to-test

#1089 Python comps version bump, zz
  generate/zz_filesystem_generated.go
  go.mod
  templates/python/flask/requirements.txt
  templates/python/wsgi/requirements.txt
Labels: approved, lgtm

#1062 [release-v1.15] Update Konflux configurations
  .tekton/docker-build.yaml
  .tekton/kn-plugin-func-func-util-115-pull-request.yaml
  .tekton/kn-plugin-func-func-util-115-push.yaml
  openshift/ci-operator/knative-images/func-util/Dockerfile
Labels: approved, lgtm, ok-to-test

#1099 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm

#1103 Add gauron to approvers
  OWNERS
Labels: approved, lgtm

#1119 add gauron to writers in 1.16
  OWNERS
Labels: approved, lgtm

#1098 [release-v1.16] Update Konflux configurations
  openshift/ci-operator/knative-images/func-util/Dockerfile
Labels: approved, lgtm, ok-to-test

#1122 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm

#1125 [release-v1.16] Update Konflux configurations
  renovate.json
Labels: approved, lgtm, ok-to-test

#1124 [release-v1.15] Update Konflux configurations
  renovate.json
Labels: approved, lgtm, ok-to-test

#1126 [release-v1.17] Update Konflux configurations
  renovate.json
Labels: approved, lgtm, ok-to-test

#1161 :robot: triggering CI on branch 'release-next' after synching from upstream/main
  ci
Labels: kind/sync-fork-to-upstream, approved, lgtm
